In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
file=pd.read_csv(r'C:\rahul\rahul\NITK\Semester IV\IET_project\samples\ml_inp.csv')

In [3]:
file.head()

0          1          2          3          4          5  \
0   71.982422  37.060639  17.937020   1.149378   8.672890   7.175745   
1   75.859375  21.687200   6.257866   6.869791   6.109959   1.776679   
2  160.087891  74.411957  33.082689  11.872473  21.443975  14.124549   
3  208.530273  87.684459  24.165588  24.848189  17.298508   9.664254   
4   56.093750  22.679705   7.738531   5.487374   7.954194   3.317685   

           6          7          8         9  ...       231        232  \
0   3.388095   3.620293   3.507729  8.622306  ...  8.622306   3.507729   
1   2.966246   1.239602   3.540910  3.552432  ...  3.552432   3.540910   
2   8.068626  14.112193  10.442393  4.824432  ...  4.824432  10.442393   
3  17.642300   8.421950   9.400841  5.681136  ...  5.681136   9.400841   
4   1.462483   2.375024   1.530923  1.209265  ...  1.209265   1.530923   

         233        234        235        236        237        238  \
0   3.620293   3.388095   7.175745   8.672890   1.149378  17.937020   
1   1.239602   2.966246   1.776679   6.109959   6.869791   6.257866   
2  14.112193   8.068626  14.124549  21.443975  11.872473  33.082689   
3   8.421950  17.642300   9.664254  17.298508  24.848189  24.165588   
4   2.375024   1.462483   3.317685   7.954194   5.487374   7.738531   

         239  ges  
0  37.060639    1  
1  21.687200    1  
2  74.411957    1  
3  87.684459    1  
4  22.679705    1  

[5 rows x 241 columns]

In [4]:
x = file.drop(columns=['ges'])
y = file['ges']

In [5]:
#for i in range(len(x.columns)):
#    if (i<120 & i>0):
#        x1[i]=x[i]*2
x1=x.iloc[:,:120]
x2=x1.iloc[:,1:120]
x3=x2*2
x3['0']=x1.iloc[:,:1]
x3.head()
#x3.append(x1.iloc[:,:0])

1          2          3          4          5          6  \
0   74.121279  35.874041   2.298757  17.345780  14.351490   6.776190   
1   43.374400  12.515733  13.739583  12.219918   3.553357   5.932493   
2  148.823915  66.165378  23.744947  42.887950  28.249098  16.137252   
3  175.368917  48.331176  49.696378  34.597017  19.328507  35.284599   
4   45.359411  15.477062  10.974747  15.908388   6.635370   2.924965   

           7          8          9         10  ...       111       112  \
0   7.240586   7.015458  17.244612  21.031209  ...  1.524345  1.559156   
1   2.479205   7.081820   7.104865   1.441310  ...  0.672121  0.933101   
2  28.224386  20.884785   9.648864  17.741076  ...  0.908628  0.636030   
3  16.843901  18.801683  11.362271   9.559265  ...  2.608076  2.133794   
4   4.750048   3.061846   2.418530   4.205261  ...  0.915893  0.715255   

        113       114       115       116       117       118       119  \
0  1.256021  0.692900  1.151182  0.841533  0.164223  1.010011  1.533135   
1  1.389408  0.719616  0.714164  0.763468  0.564713  0.868154  0.470731   
2  0.974683  2.537122  3.263043  2.300307  1.956073  2.852104  2.698683   
3  1.300433  1.243745  1.436777  1.554751  1.630784  2.511762  2.058786   
4  0.276560  0.260537  0.829875  1.334538  1.669857  1.486957  0.654216   

            0  
0   71.982422  
1   75.859375  
2  160.087891  
3  208.530273  
4   56.093750  

[5 rows x 120 columns]

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x3, y, test_size=0.25, random_state=42)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = pd.DataFrame(sc.fit_transform(x_train))
x_test = pd.DataFrame(sc.transform(x_test))

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

lr_grid = {'max_depth' : [4,8,16,32,64,128],
           'criterion' : ['entropy','gini']}

clf = RandomForestClassifier(n_estimators=20, max_features='sqrt', random_state=42)

gs = GridSearchCV(estimator = clf, param_grid=lr_grid,cv = 5)
gs.fit(x_train,y_train)
y_pred = gs.predict(x_test)


C:\sbasu\software\anaconda\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


In [9]:
gs.best_params_

{'criterion': 'entropy', 'max_depth': 4}

In [10]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print('Classification Report: \n', classification_report(y_test,y_pred))
print('Confusion Matrix: \n', confusion_matrix(y_test,y_pred))

Classification Report: 
               precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       1.00      0.50      0.67         2
           3       1.00      0.50      0.67         2
           4       0.33      0.50      0.40         2
           5       0.00      0.00      0.00         1

    accuracy                           0.38         8
   macro avg       0.47      0.30      0.35         8
weighted avg       0.58      0.38      0.43         8

Confusion Matrix: 
 [[0 0 0 1 0]
 [1 1 0 0 0]
 [0 0 1 1 0]
 [1 0 0 1 0]
 [1 0 0 0 0]]


C:\sbasu\software\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\sbasu\software\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\sbasu\software\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
