In [1]:
import pandas as pd

file=pd.read_csv(r'C:\rahul\rahul\NITK\Semester IV\IET_project\samples\samples2.csv')

In [2]:
file.columns

Index(['sample', 'op_cl_op1', 'op_cl_op2', 'op_cl_op3', 'op_cl_op4',
       'op_cl_op5', 'op_cl_op6', 'op_cl_op7', 'op_cl_op8', 'op_cl_op9',
       ...
       'pn_op_pn13', 'pn_op_pn14', 'pn_op_pn15', 'pn_op_pn16', 'pn_op_pn17',
       'pn_op_pn18', 'pn_op_pn19', 'pn_op_pn20', 'pn_op_pn21', 'pn_op_pn22'],
      dtype='object', length=109)

In [3]:
sample_legend={1:'op_cl_op',2:'cl_rd_cl',3:'ex_fl_ex',4:'sp_pr_sp',5:'pn_op_pn'}
filepath=r'C:\rahul\rahul\NITK\Semester IV\IET_project\gesture'

In [4]:
for i in range(5):
    for j in range(22):
        l=1
        if j>=11:
            l=2
            j=j-11
        fold_n='\p'+str(j+1)
        file_n='\g'+str(i+1)+'t'+str(l)+'.csv'
        col_n=sample_legend[i+1]+str(j+1)
        path=filepath+fold_n+file_n
        #print(repr(path))
        f=file[col_n]
        f.to_csv(path,columns=[col_n],index=False)

In [5]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 762 entries, 0 to 761
Columns: 109 entries, sample to pn_op_pn22
dtypes: float64(108), int64(1)
memory usage: 649.0 KB


In [6]:
file.isnull().sum()

sample        355
op_cl_op1     356
op_cl_op2     376
op_cl_op3     319
op_cl_op4     361
             ... 
pn_op_pn18    378
pn_op_pn19    414
pn_op_pn20    415
pn_op_pn21    398
pn_op_pn22    360
Length: 109, dtype: int64

In [7]:
file.describe()

sample   op_cl_op1   op_cl_op2   op_cl_op3   op_cl_op4   op_cl_op5  \
count  407.000000  406.000000  386.000000  443.000000  401.000000  355.000000   
mean   204.000000   76.891626   52.606218   92.223476  135.294264   39.126761   
std    117.635029   76.917869   29.723756   94.507378  110.019286   30.068345   
min      1.000000    1.000000   16.000000   21.000000   46.000000    2.000000   
25%    102.500000   21.000000   36.000000   46.000000   72.000000   19.000000   
50%    204.000000   25.000000   40.000000   55.000000   77.000000   24.000000   
75%    305.500000  141.000000   65.750000   64.000000  198.000000   58.000000   
max    407.000000  231.000000  134.000000  465.000000  484.000000  133.000000   

        op_cl_op6   op_cl_op7   op_cl_op8   op_cl_op9  ...  pn_op_pn13  \
count  358.000000  349.000000  401.000000  354.000000  ...  353.000000   
mean    45.424581  170.071633  150.079800  334.288136  ...  423.501416   
std     35.938068   87.814414   32.990735   18.485934  ...   19.117627   
min     16.000000    0.000000    7.000000  302.000000  ...  387.000000   
25%     24.000000  132.000000  132.000000  319.000000  ...  408.000000   
50%     28.500000  140.000000  136.000000  336.000000  ...  423.000000   
75%     63.750000  172.000000  161.000000  346.000000  ...  440.000000   
max    382.000000  633.000000  301.000000  389.000000  ...  469.000000   

       pn_op_pn14  pn_op_pn15  pn_op_pn16  pn_op_pn17  pn_op_pn18  pn_op_pn19  \
count  368.000000  310.000000  375.000000  412.000000  384.000000  348.000000   
mean   435.510870  295.861290  281.506667  322.548544  330.927083  369.836207   
std     28.166397    7.376389   23.548660   31.231653   29.245069   16.209513   
min      0.000000  282.000000    1.000000    3.000000    7.000000  334.000000   
25%    422.000000  291.000000  271.000000  313.000000  326.000000  357.000000   
50%    436.000000  295.000000  284.000000  318.000000  333.000000  372.000000   
75%    448.000000  299.000000  292.000000  326.000000  340.000000  382.000000   
max    478.000000  323.000000  305.000000  413.000000  360.000000  410.000000   

       pn_op_pn20  pn_op_pn21  pn_op_pn22  
count  347.000000  364.000000  402.000000  
mean   377.723343  178.532967  397.101990  
std     11.535750   19.901313   47.117956  
min    347.000000    2.000000    7.000000  
25%    370.000000  168.000000  382.000000  
50%    378.000000  177.000000  393.000000  
75%    386.000000  191.000000  406.000000  
max    417.000000  214.000000  610.000000  

[8 rows x 109 columns]

In [8]:
N=400
l=20
p=N/l


In [9]:
p=pd.DataFrame()
for j in range(11):
    for i in range(5):
        l=1
        filepath=r'C:\rahul\rahul\NITK\Semester IV\IET_project\gesture'
        filepath=r'C:\rahul\rahul\NITK\Semester IV\IET_project\gesture\p1'
        #fold_n='\p'+str(j+1)
        file_n='\g'+str(i+1)+'t'+str(l)+'.csv'
        col_n=sample_legend[i+1]+str(1)
        #path=filepath+fold_n+file_n
        path=filepath+file_n
        #pd_n='f'+
        #print(repr(path))
        f=pd.read_csv(path,index_col=False)
        p[col_n]=f
#p.head()    

In [10]:
p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 762 entries, 0 to 761
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   op_cl_op1  406 non-null    float64
 1   cl_rd_cl1  407 non-null    float64
 2   ex_fl_ex1  341 non-null    float64
 3   sp_pr_sp1  762 non-null    int64  
 4   pn_op_pn1  360 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 29.9 KB


In [11]:
p1=p[:400]

In [12]:
p1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   op_cl_op1  400 non-null    float64
 1   cl_rd_cl1  400 non-null    float64
 2   ex_fl_ex1  341 non-null    float64
 3   sp_pr_sp1  400 non-null    int64  
 4   pn_op_pn1  360 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 15.8 KB


In [13]:
p1=p1.fillna(0)

In [14]:
N=400
l=20
p=int(N/l)
import numpy as np

In [15]:
from statistics import variance as var
from statistics import mean as mean

def rms(x):
    # x is array of 20 elements
    r,s=0,0
    for i in range(20):
        s+=x[i]**2
    r=np.sqrt(s/2)
    return r

def iemg(x):
    # x is array of 20 elements
    s=0
    for i in range(20):
        s+=x[i]
    #r=np.sqrt(s/2)
    return s
#def var(x):
    # x is array of 20 elements

In [16]:
st=0
r=np.zeros((11,5,20),dtype=np.float32)
v=np.zeros((11,5,20),dtype=np.float32)
m=np.zeros((11,5,20),dtype=np.float32)
e=np.zeros((11,5,20),dtype=np.float32)
w=np.zeros((11,5,20))
print(p)
for k in range(11):
    for i in range(5):
        st=0
        for j in range(p):
            x=list(p1[sample_legend[i+1]+str(1)][st:st+l])
            #print(x, st)
            r[k][i][j]=rms(x)
            print(r[0][i][j])
            v[k][i][j]=var(x)
            print(v[0][i][j])
            m[k][i][j]=mean(x)
            print(m[0][i][j])
            e[k][i][j]=iemg(x)
            print(e[0][i][j])
            w[k][i][j]=len(x)
            st=st+l
            if (p-j)==1:
                break
        

20
644.29144
2198.9973
198.55
3971.0
646.5273
2251.608
199.15
3983.0
637.6014
2169.4185
196.45
3929.0
541.54456
9360.366
142.95
2859.0
65.757126
4.1157894
20.7
414.0
66.63708
5.4184213
20.95
419.0
70.22108
4.936842
22.1
442.0
66.64458
5.523684
20.95
419.0
123.19294
739.5237
28.55
571.0
455.65338
1924.4631
137.6
2752.0
443.5871
389.31317
138.95
2779.0
507.92963
2176.6816
154.05
3081.0
358.15988
521.8395
111.05
2221.0
98.17332
110.85263
29.3
586.0
82.870384
8.576316
26.05
521.0
76.48856
6.9973683
24.05
481.0
74.833145
8.157895
23.5
470.0
62.39391
5.4105263
19.6
392.0
63.45865
7.042105
19.9
398.0
64.01172
8.155263
20.05
401.0
84.60792
17.102633
26.45
529.0
81.237305
7.523684
25.55
511.0
84.397865
10.578947
26.5
530.0
98.75221
14.947369
31.0
620.0
105.58882
13.326316
33.2
664.0
388.08505
518.4316
120.7
2414.0
447.66672
419.50262
140.15
2803.0
463.11877
322.88422
145.4
2908.0
411.6631
954.1342
126.65
2533.0
174.64964
55.460526
54.75
1095.0
152.52213
13.357895
48.1
962.0
150.71663
21.102633


318.7601
84.88421
100.4
2008.0
194.30002
353.08157
58.65
1173.0
108.9977
8.5552635
34.35
687.0
105.61723
6.957895
33.3
666.0
94.74967
7.0815787
29.85
597.0
66.70082
21.621052
20.6
412.0
58.116264
4.9342103
18.25
365.0
350.99075
814.6816
107.45
2149.0
416.07452
378.69473
130.2
2604.0
467.6056
270.0
147.0
2940.0
442.0792
234.10527
139.0
2780.0
491.907
197.62895
154.95
3099.0
489.5559
490.11578
153.3
3066.0
436.02466
4074.1553
123.05
2461.0
56.841885
2.831579
17.9
358.0
55.204166
3.9236841
17.35
347.0
58.655777
3.8394737
18.45
369.0
73.229095
10.05
22.95
459.0
232.35533
2226.958
57.3
1146.0
605.1
180.83157
190.9
3818.0
541.0379
176.67369
170.6
3412.0
554.47815
125.89474
175.0
3500.0
542.5933
300.19736
170.75
3415.0
472.93817
190.47105
148.95
2979.0
470.18506
276.37894
147.8
2956.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
644.29144
2198.9973
198.55
3971.0
646.5273
2251.608
199.15
3983.0
637.6014
2169.4185
196.45
3929.0
541.54456
9360.366
142.95
2859.0
65.757126
4.1157894
20.7
414.0
66.63708
5.41842

87.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
137.21152
453.77896
38.1
762.0
108.78419
14.484211
34.2
684.0
101.13605
15.565789
31.75
635.0
84.01785
9.410526
26.4
528.0
71.21797
5.726316
22.4
448.0
74.44125
4.4710526
23.45
469.0
76.1643
4.3157897
24.0
480.0
82.188805
15.8
25.7
514.0
110.02273
6.7473683
34.7
694.0
563.25214
2470.8843
171.4
3428.0
380.33078
482.55527
118.35
2367.0
437.87042
1351.5658
133.75
2675.0
459.1035
811.9474
142.5
2850.0
318.7601
84.88421
100.4
2008.0
194.30002
353.08157
58.65
1173.0
108.9977
8.5552635
34.35
687.0
105.61723
6.957895
33.3
666.0
94.74967
7.0815787
29.85
597.0
66.70082
21.621052
20.6
412.0
58.116264
4.9342103
18.25
365.0
350.99075
814.6816
107.45
2149.0
416.07452
378.69473
130.2
2604.0
467.6056
270.0
147.0
2940.0
442.0792
234.10527
139.0
2780.0
491.907
197.62895
154.95
3099.0
489.5559
490.11578
153.3
3066.0
436.02466
4074.1553
123.05
2461.0
56.841885
2.831579
17.9
358.0
55.204166
3.9236841
17.35
347.0
58.655777
3.8394737
18.45
369.0
73.229095
10.05
22.95
459.

118.8
2376.0
325.98697
159.18684
102.35
2047.0
303.47406
84.05
95.55
1911.0
243.48717
96.46316
76.4
1528.0
213.27448
48.62105
67.1
1342.0
192.15489
696.6816
55.05
1101.0
77.688484
11.186842
24.35
487.0
241.8698
1117.3263
69.2
1384.0
152.16438
22.094736
47.9
958.0
147.69733
5.5026317
46.65
933.0
155.7482
10.5552635
49.15
983.0
144.7964
8.536842
45.7
914.0
146.2703
15.042106
46.1
922.0
464.82846
8444.893
116.55
2331.0
667.4736
1836.3053
206.9
4138.0
367.4221
240.90526
115.2
2304.0
487.6269
1597.2211
149.2
2984.0
403.29767
382.83157
126.1
2522.0
378.81592
1002.1974
115.75
2315.0
383.89713
556.9053
119.2
2384.0
300.25906
20.028948
94.85
1897.0
305.48322
81.642105
96.2
1924.0
337.66107
307.72632
105.4
2108.0
261.27188
38.463158
82.4
1648.0
61.51829
378.45
4.35
87.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
137.21152
453.77896
38.1
762.0
108.78419
14.484211
34.2
684.0
101.13605
15.565789
31.75
635.0
84.01785
9.410526
26.4
528.0
71.21797
5.726316
22.4
448.0
74.44125
4.4710526
23.45
469.0
76.1643
4.3157

In [17]:
r

array([[[644.29144 , 646.5273  , 637.6014  , ...,  62.39391 ,
          63.45865 ,  64.01172 ],
        [ 84.60792 ,  81.237305,  84.397865, ..., 213.27448 ,
         192.15489 ,  77.688484],
        [241.8698  , 152.16438 , 147.69733 , ...,  61.51829 ,
           0.      ,   0.      ],
        [137.21152 , 108.78419 , 101.13605 , ...,  94.74967 ,
          66.70082 ,  58.116264],
        [350.99075 , 416.07452 , 467.6056  , ..., 470.18506 ,
           0.      ,   0.      ]],

       [[644.29144 , 646.5273  , 637.6014  , ...,  62.39391 ,
          63.45865 ,  64.01172 ],
        [ 84.60792 ,  81.237305,  84.397865, ..., 213.27448 ,
         192.15489 ,  77.688484],
        [241.8698  , 152.16438 , 147.69733 , ...,  61.51829 ,
           0.      ,   0.      ],
        [137.21152 , 108.78419 , 101.13605 , ...,  94.74967 ,
          66.70082 ,  58.116264],
        [350.99075 , 416.07452 , 467.6056  , ..., 470.18506 ,
           0.      ,   0.      ]],

       [[644.29144 , 646.5273  , 637

In [18]:
v

array([[[2198.9973   , 2251.608    , 2169.4185   , ...,    5.4105263,
            7.042105 ,    8.155263 ],
        [  17.102633 ,    7.523684 ,   10.578947 , ...,   48.62105  ,
          696.6816   ,   11.186842 ],
        [1117.3263   ,   22.094736 ,    5.5026317, ...,  378.45     ,
            0.       ,    0.       ],
        [ 453.77896  ,   14.484211 ,   15.565789 , ...,    7.0815787,
           21.621052 ,    4.9342103],
        [ 814.6816   ,  378.69473  ,  270.       , ...,  276.37894  ,
            0.       ,    0.       ]],

       [[2198.9973   , 2251.608    , 2169.4185   , ...,    5.4105263,
            7.042105 ,    8.155263 ],
        [  17.102633 ,    7.523684 ,   10.578947 , ...,   48.62105  ,
          696.6816   ,   11.186842 ],
        [1117.3263   ,   22.094736 ,    5.5026317, ...,  378.45     ,
            0.       ,    0.       ],
        [ 453.77896  ,   14.484211 ,   15.565789 , ...,    7.0815787,
           21.621052 ,    4.9342103],
        [ 814.6816   ,  37

In [19]:
m

array([[[198.55, 199.15, 196.45, ...,  19.6 ,  19.9 ,  20.05],
        [ 26.45,  25.55,  26.5 , ...,  67.1 ,  55.05,  24.35],
        [ 69.2 ,  47.9 ,  46.65, ...,   4.35,   0.  ,   0.  ],
        [ 38.1 ,  34.2 ,  31.75, ...,  29.85,  20.6 ,  18.25],
        [107.45, 130.2 , 147.  , ..., 147.8 ,   0.  ,   0.  ]],

       [[198.55, 199.15, 196.45, ...,  19.6 ,  19.9 ,  20.05],
        [ 26.45,  25.55,  26.5 , ...,  67.1 ,  55.05,  24.35],
        [ 69.2 ,  47.9 ,  46.65, ...,   4.35,   0.  ,   0.  ],
        [ 38.1 ,  34.2 ,  31.75, ...,  29.85,  20.6 ,  18.25],
        [107.45, 130.2 , 147.  , ..., 147.8 ,   0.  ,   0.  ]],

       [[198.55, 199.15, 196.45, ...,  19.6 ,  19.9 ,  20.05],
        [ 26.45,  25.55,  26.5 , ...,  67.1 ,  55.05,  24.35],
        [ 69.2 ,  47.9 ,  46.65, ...,   4.35,   0.  ,   0.  ],
        [ 38.1 ,  34.2 ,  31.75, ...,  29.85,  20.6 ,  18.25],
        [107.45, 130.2 , 147.  , ..., 147.8 ,   0.  ,   0.  ]],

       ...,

       [[198.55, 199.15, 196.45, ...

In [20]:
w

array([[[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.]],

       [[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.]],

       [[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.]],

       ...,

       [[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.]],

       [[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 

In [21]:
r[0][0]

array([644.29144 , 646.5273  , 637.6014  , 541.54456 ,  65.757126,
        66.63708 ,  70.22108 ,  66.64458 , 123.19294 , 455.65338 ,
       443.5871  , 507.92963 , 358.15988 ,  98.17332 ,  82.870384,
        76.48856 ,  74.833145,  62.39391 ,  63.45865 ,  64.01172 ],
      dtype=float32)

In [22]:
r[0], v[0], m[0], e[0]

(array([[644.29144 , 646.5273  , 637.6014  , 541.54456 ,  65.757126,
          66.63708 ,  70.22108 ,  66.64458 , 123.19294 , 455.65338 ,
         443.5871  , 507.92963 , 358.15988 ,  98.17332 ,  82.870384,
          76.48856 ,  74.833145,  62.39391 ,  63.45865 ,  64.01172 ],
        [ 84.60792 ,  81.237305,  84.397865,  98.75221 , 105.58882 ,
         388.08505 , 447.66672 , 463.11877 , 411.6631  , 174.64964 ,
         152.52213 , 150.71663 , 153.40633 , 436.61996 , 325.98697 ,
         303.47406 , 243.48717 , 213.27448 , 192.15489 ,  77.688484],
        [241.8698  , 152.16438 , 147.69733 , 155.7482  , 144.7964  ,
         146.2703  , 464.82846 , 667.4736  , 367.4221  , 487.6269  ,
         403.29767 , 378.81592 , 383.89713 , 300.25906 , 305.48322 ,
         337.66107 , 261.27188 ,  61.51829 ,   0.      ,   0.      ],
        [137.21152 , 108.78419 , 101.13605 ,  84.01785 ,  71.21797 ,
          74.44125 ,  76.1643  ,  82.188805, 110.02273 , 563.25214 ,
         380.33078 , 437.87042 

In [23]:
g=pd.DataFrame()
for i in range(5):
    g[i+1]=pd.concat([pd.Series(r[0][i]), pd.Series(v[0][i]), pd.Series(m[0][i]), pd.Series(e[0][i])], ignore_index=True)

In [24]:
g.head()

1           2           3           4           5
0  644.291443   84.607918  241.869797  137.211517  350.990753
1  646.527283   81.237305  152.164383  108.784187  416.074524
2  637.601379   84.397865  147.697327  101.136047  467.605591
3  541.544556   98.752213  155.748199   84.017853  442.079193
4   65.757126  105.588821  144.796402   71.217972  491.907013

In [25]:
g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   1       80 non-null     float32
 1   2       80 non-null     float32
 2   3       80 non-null     float32
 3   4       80 non-null     float32
 4   5       80 non-null     float32
dtypes: float32(5)
memory usage: 1.7 KB


In [30]:
g[0:20]

1           2           3           4           5
0   644.291443   84.607918  241.869797  137.211517  350.990753
1   646.527283   81.237305  152.164383  108.784187  416.074524
2   637.601379   84.397865  147.697327  101.136047  467.605591
3   541.544556   98.752213  155.748199   84.017853  442.079193
4    65.757126  105.588821  144.796402   71.217972  491.907013
5    66.637077  388.085052  146.270294   74.441254  489.555908
6    70.221077  447.666718  464.828461   76.164299  436.024658
7    66.644577  463.118774  667.473572   82.188805   56.841885
8   123.192940  411.663086  367.422089  110.022728   55.204166
9   455.653381  174.649643  487.626892  563.252136   58.655777
10  443.587097  152.522125  403.297668  380.330780   73.229095
11  507.929626  150.716629  378.815918  437.870422  232.355331
12  358.159882  153.406326  383.897125  459.103485  605.099976
13   98.173317  436.619965  300.259064  318.760101  541.037903
14   82.870384  325.986969  305.483215  194.300018  554.478149
15   76.488564  303.474060  337.661072  108.997704  542.593323
16   74.833145  243.487167  261.271881  105.617233  472.938171
17   62.393909  213.274475   61.518291   94.749672  470.185059
18   63.458649  192.154892    0.000000   66.700821    0.000000
19   64.011719   77.688484    0.000000   58.116264    0.000000

In [38]:
rm=np.array(g[0:20].transpose())
rm.shape
a=np.reshape(rm,100)

In [43]:
vr=np.array(g[20:40].transpose())
vr.shape
b=np.reshape(vr,100)

mn=np.array(g[40:60].transpose())
mn.shape
c=np.reshape(mn,100)

ie=np.array(g[60:80].transpose())
ie.shape
d=np.reshape(ie,100)

In [44]:
features=pd.DataFrame([a,b,c,d])
features.shape

(4, 100)

In [45]:
features.head()

0            1            2            3           4           5   \
0   644.291443   646.527283   637.601379   541.544556   65.757126   66.637077   
1  2198.997314  2251.607910  2169.418457  9360.366211    4.115789    5.418421   
2   198.550003   199.149994   196.449997   142.949997   20.700001   20.950001   
3  3971.000000  3983.000000  3929.000000  2859.000000  414.000000  419.000000   

           6           7           8            9   ...          90  \
0   70.221077   66.644577  123.192940   455.653381  ...   73.229095   
1    4.936842    5.523684  739.523682  1924.463135  ...   10.050000   
2   22.100000   20.950001   28.549999   137.600006  ...   22.950001   
3  442.000000  419.000000  571.000000  2752.000000  ...  459.000000   

            91           92           93           94           95  \
0   232.355331   605.099976   541.037903   554.478149   542.593323   
1  2226.958008   180.831573   176.673691   125.894737   300.197357   
2    57.299999   190.899994   170.600006   175.000000   170.750000   
3  1146.000000  3818.000000  3412.000000  3500.000000  3415.000000   

            96           97   98   99  
0   472.938171   470.185059  0.0  0.0  
1   190.471054   276.378937  0.0  0.0  
2   148.949997   147.800003  0.0  0.0  
3  2979.000000  2956.000000  0.0  0.0  

[4 rows x 100 columns]

In [48]:
f2=features.transpose()
f2.head()

0            1           2       3
0  644.291443  2198.997314  198.550003  3971.0
1  646.527283  2251.607910  199.149994  3983.0
2  637.601379  2169.418457  196.449997  3929.0
3  541.544556  9360.366211  142.949997  2859.0
4   65.757126     4.115789   20.700001   414.0

In [49]:
f2.shape

(100, 4)

In [40]:
a


array([644.29144 , 646.5273  , 637.6014  , 541.54456 ,  65.757126,
        66.63708 ,  70.22108 ,  66.64458 , 123.19294 , 455.65338 ,
       443.5871  , 507.92963 , 358.15988 ,  98.17332 ,  82.870384,
        76.48856 ,  74.833145,  62.39391 ,  63.45865 ,  64.01172 ,
        84.60792 ,  81.237305,  84.397865,  98.75221 , 105.58882 ,
       388.08505 , 447.66672 , 463.11877 , 411.6631  , 174.64964 ,
       152.52213 , 150.71663 , 153.40633 , 436.61996 , 325.98697 ,
       303.47406 , 243.48717 , 213.27448 , 192.15489 ,  77.688484,
       241.8698  , 152.16438 , 147.69733 , 155.7482  , 144.7964  ,
       146.2703  , 464.82846 , 667.4736  , 367.4221  , 487.6269  ,
       403.29767 , 378.81592 , 383.89713 , 300.25906 , 305.48322 ,
       337.66107 , 261.27188 ,  61.51829 ,   0.      ,   0.      ,
       137.21152 , 108.78419 , 101.13605 ,  84.01785 ,  71.21797 ,
        74.44125 ,  76.1643  ,  82.188805, 110.02273 , 563.25214 ,
       380.33078 , 437.87042 , 459.1035  , 318.7601  , 194.300

In [41]:
a.shape

(100,)