In [2]:
import pandas as pd

file=pd.read_csv(r'C:\rahul\rahul\NITK\Semester IV\IET_project\samples\samples2.csv')

In [3]:
file.columns

Index(['sample', 'op_cl_op1', 'op_cl_op2', 'op_cl_op3', 'op_cl_op4',
       'op_cl_op5', 'op_cl_op6', 'op_cl_op7', 'op_cl_op8', 'op_cl_op9',
       ...
       'pn_op_pn13', 'pn_op_pn14', 'pn_op_pn15', 'pn_op_pn16', 'pn_op_pn17',
       'pn_op_pn18', 'pn_op_pn19', 'pn_op_pn20', 'pn_op_pn21', 'pn_op_pn22'],
      dtype='object', length=109)

In [4]:
sample_legend={1:'op_cl_op',2:'cl_rd_cl',3:'ex_fl_ex',4:'sp_pr_sp',5:'pn_op_pn'}
filepath=r'C:\rahul\rahul\NITK\Semester IV\IET_project\gesture'

In [5]:
for i in range(5):
    for j in range(22):
        l=1
        if j>=11:
            l=2
            j=j-11
        fold_n='\p'+str(j+1)
        file_n='\g'+str(i+1)+'t'+str(l)+'.csv'
        col_n=sample_legend[i+1]+str(j+1)
        path=filepath+fold_n+file_n
        #print(repr(path))
        f=file[col_n]
        f.to_csv(path,columns=[col_n],index=False)

In [6]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 762 entries, 0 to 761
Columns: 109 entries, sample to pn_op_pn22
dtypes: float64(108), int64(1)
memory usage: 649.0 KB


In [7]:
file.isnull().sum()

sample        355
op_cl_op1     356
op_cl_op2     376
op_cl_op3     319
op_cl_op4     361
             ... 
pn_op_pn18    378
pn_op_pn19    414
pn_op_pn20    415
pn_op_pn21    398
pn_op_pn22    360
Length: 109, dtype: int64

In [8]:
file.describe()

sample   op_cl_op1   op_cl_op2   op_cl_op3   op_cl_op4   op_cl_op5  \
count  407.000000  406.000000  386.000000  443.000000  401.000000  355.000000   
mean   204.000000   76.891626   52.606218   92.223476  135.294264   39.126761   
std    117.635029   76.917869   29.723756   94.507378  110.019286   30.068345   
min      1.000000    1.000000   16.000000   21.000000   46.000000    2.000000   
25%    102.500000   21.000000   36.000000   46.000000   72.000000   19.000000   
50%    204.000000   25.000000   40.000000   55.000000   77.000000   24.000000   
75%    305.500000  141.000000   65.750000   64.000000  198.000000   58.000000   
max    407.000000  231.000000  134.000000  465.000000  484.000000  133.000000   

        op_cl_op6   op_cl_op7   op_cl_op8   op_cl_op9  ...  pn_op_pn13  \
count  358.000000  349.000000  401.000000  354.000000  ...  353.000000   
mean    45.424581  170.071633  150.079800  334.288136  ...  423.501416   
std     35.938068   87.814414   32.990735   18.485934  ...   19.117627   
min     16.000000    0.000000    7.000000  302.000000  ...  387.000000   
25%     24.000000  132.000000  132.000000  319.000000  ...  408.000000   
50%     28.500000  140.000000  136.000000  336.000000  ...  423.000000   
75%     63.750000  172.000000  161.000000  346.000000  ...  440.000000   
max    382.000000  633.000000  301.000000  389.000000  ...  469.000000   

       pn_op_pn14  pn_op_pn15  pn_op_pn16  pn_op_pn17  pn_op_pn18  pn_op_pn19  \
count  368.000000  310.000000  375.000000  412.000000  384.000000  348.000000   
mean   435.510870  295.861290  281.506667  322.548544  330.927083  369.836207   
std     28.166397    7.376389   23.548660   31.231653   29.245069   16.209513   
min      0.000000  282.000000    1.000000    3.000000    7.000000  334.000000   
25%    422.000000  291.000000  271.000000  313.000000  326.000000  357.000000   
50%    436.000000  295.000000  284.000000  318.000000  333.000000  372.000000   
75%    448.000000  299.000000  292.000000  326.000000  340.000000  382.000000   
max    478.000000  323.000000  305.000000  413.000000  360.000000  410.000000   

       pn_op_pn20  pn_op_pn21  pn_op_pn22  
count  347.000000  364.000000  402.000000  
mean   377.723343  178.532967  397.101990  
std     11.535750   19.901313   47.117956  
min    347.000000    2.000000    7.000000  
25%    370.000000  168.000000  382.000000  
50%    378.000000  177.000000  393.000000  
75%    386.000000  191.000000  406.000000  
max    417.000000  214.000000  610.000000  

[8 rows x 109 columns]

In [9]:
N=400
l=20
p=N/l


In [11]:
p=pd.DataFrame()
for j in range(11):
    for i in range(5):
        l=1
        #filepath=r'C:\rahul\rahul\NITK\Semester IV\IET_project\gesture'
        filepath=r'C:\rahul\rahul\NITK\Semester IV\IET_project\gesture'
        fold_n='\p'+str(j+1)
        file_n='\g'+str(i+1)+'t'+str(l)+'.csv'
        col_n=sample_legend[i+1]+str(1)
        path=filepath+fold_n+file_n
        #path=filepath+file_n
        pd_n='f'+str(j+1)
        #print(repr(path))
        pd_n=pd.DataFrame()
        pd_n=pd.read_csv(path,index_col=False)
        pd_n[col_n]=f
        pd_n.head(3)
#p.head()    

In [12]:
f1.info()

NameError: name 'f1' is not defined

In [11]:
p1=p[:400]

In [12]:
p1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   op_cl_op1  400 non-null    float64
 1   cl_rd_cl1  400 non-null    float64
 2   ex_fl_ex1  341 non-null    float64
 3   sp_pr_sp1  400 non-null    int64  
 4   pn_op_pn1  360 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 15.8 KB


In [13]:
p1=p1.fillna(0)

In [14]:
N=400
l=20
p=int(N/l)
import numpy as np

In [27]:
from statistics import variance as var
from statistics import mean as mean

def rms(x):
    # x is array of 20 elements
    r,s=0,0
    for i in range(20):
        s+=x[i]**2
    r=np.sqrt(s/2)
    return r

def iemg(x):
    # x is array of 20 elements
    s=0
    for i in range(20):
        s+=x[i]
    #r=np.sqrt(s/2)
    return s
#def var(x):
    # x is array of 20 elements

In [28]:
st=0
r=np.zeros((11,5,20),dtype=np.float32)
v=np.zeros((11,5,20),dtype=np.float32)
m=np.zeros((11,5,20),dtype=np.float32)
e=np.zeros((11,5,20),dtype=np.float32)
w=np.zeros((11,5,20))
print(p)
for k in range(11):
    for i in range(5):
        st=0
        for j in range(p):
            x=list(p1[sample_legend[i+1]+str(1)][st:st+l])
            #print(x, st)
            r[k][i][j]=rms(x)
            print(r[0][i][j])
            v[k][i][j]=var(x)
            print(v[0][i][j])
            m[k][i][j]=mean(x)
            print(m[0][i][j])
            e[k][i][j]=iemg(x)
            print(e[0][i][j])
            w[k][i][j]=len(x)
            st=st+l
            if (p-j)==1:
                break
        

20
644.29144
2198.9973
198.55
3971.0
646.5273
2251.608
199.15
3983.0
637.6014
2169.4185
196.45
3929.0
541.54456
9360.366
142.95
2859.0
65.757126
4.1157894
20.7
414.0
66.63708
5.4184213
20.95
419.0
70.22108
4.936842
22.1
442.0
66.64458
5.523684
20.95
419.0
123.19294
739.5237
28.55
571.0
455.65338
1924.4631
137.6
2752.0
443.5871
389.31317
138.95
2779.0
507.92963
2176.6816
154.05
3081.0
358.15988
521.8395
111.05
2221.0
98.17332
110.85263
29.3
586.0
82.870384
8.576316
26.05
521.0
76.48856
6.9973683
24.05
481.0
74.833145
8.157895
23.5
470.0
62.39391
5.4105263
19.6
392.0
63.45865
7.042105
19.9
398.0
64.01172
8.155263
20.05
401.0
84.60792
17.102633
26.45
529.0
81.237305
7.523684
25.55
511.0
84.397865
10.578947
26.5
530.0
98.75221
14.947369
31.0
620.0
105.58882
13.326316
33.2
664.0
388.08505
518.4316
120.7
2414.0
447.66672
419.50262
140.15
2803.0
463.11877
322.88422
145.4
2908.0
411.6631
954.1342
126.65
2533.0
174.64964
55.460526
54.75
1095.0
152.52213
13.357895
48.1
962.0
150.71663
21.102633


10.05
22.95
459.0
232.35533
2226.958
57.3
1146.0
605.1
180.83157
190.9
3818.0
541.0379
176.67369
170.6
3412.0
554.47815
125.89474
175.0
3500.0
542.5933
300.19736
170.75
3415.0
472.93817
190.47105
148.95
2979.0
470.18506
276.37894
147.8
2956.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
644.29144
2198.9973
198.55
3971.0
646.5273
2251.608
199.15
3983.0
637.6014
2169.4185
196.45
3929.0
541.54456
9360.366
142.95
2859.0
65.757126
4.1157894
20.7
414.0
66.63708
5.4184213
20.95
419.0
70.22108
4.936842
22.1
442.0
66.64458
5.523684
20.95
419.0
123.19294
739.5237
28.55
571.0
455.65338
1924.4631
137.6
2752.0
443.5871
389.31317
138.95
2779.0
507.92963
2176.6816
154.05
3081.0
358.15988
521.8395
111.05
2221.0
98.17332
110.85263
29.3
586.0
82.870384
8.576316
26.05
521.0
76.48856
6.9973683
24.05
481.0
74.833145
8.157895
23.5
470.0
62.39391
5.4105263
19.6
392.0
63.45865
7.042105
19.9
398.0
64.01172
8.155263
20.05
401.0
84.60792
17.102633
26.45
529.0
81.237305
7.523684
25.55
511.0
84.397865
10.578947
26.5
530.0
98.7

139.0
2780.0
491.907
197.62895
154.95
3099.0
489.5559
490.11578
153.3
3066.0
436.02466
4074.1553
123.05
2461.0
56.841885
2.831579
17.9
358.0
55.204166
3.9236841
17.35
347.0
58.655777
3.8394737
18.45
369.0
73.229095
10.05
22.95
459.0
232.35533
2226.958
57.3
1146.0
605.1
180.83157
190.9
3818.0
541.0379
176.67369
170.6
3412.0
554.47815
125.89474
175.0
3500.0
542.5933
300.19736
170.75
3415.0
472.93817
190.47105
148.95
2979.0
470.18506
276.37894
147.8
2956.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
644.29144
2198.9973
198.55
3971.0
646.5273
2251.608
199.15
3983.0
637.6014
2169.4185
196.45
3929.0
541.54456
9360.366
142.95
2859.0
65.757126
4.1157894
20.7
414.0
66.63708
5.4184213
20.95
419.0
70.22108
4.936842
22.1
442.0
66.64458
5.523684
20.95
419.0
123.19294
739.5237
28.55
571.0
455.65338
1924.4631
137.6
2752.0
443.5871
389.31317
138.95
2779.0
507.92963
2176.6816
154.05
3081.0
358.15988
521.8395
111.05
2221.0
98.17332
110.85263
29.3
586.0
82.870384
8.576316
26.05
521.0
76.48856
6.9973683
24.05
481.0
7

180.83157
190.9
3818.0
541.0379
176.67369
170.6
3412.0
554.47815
125.89474
175.0
3500.0
542.5933
300.19736
170.75
3415.0
472.93817
190.47105
148.95
2979.0
470.18506
276.37894
147.8
2956.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [17]:
r

array([[[644.29144 , 646.5273  , 637.6014  , ...,  62.39391 ,
          63.45865 ,  64.01172 ],
        [ 84.60792 ,  81.237305,  84.397865, ..., 213.27448 ,
         192.15489 ,  77.688484],
        [241.8698  , 152.16438 , 147.69733 , ...,  61.51829 ,
           0.      ,   0.      ],
        [137.21152 , 108.78419 , 101.13605 , ...,  94.74967 ,
          66.70082 ,  58.116264],
        [350.99075 , 416.07452 , 467.6056  , ..., 470.18506 ,
           0.      ,   0.      ]],

       [[644.29144 , 646.5273  , 637.6014  , ...,  62.39391 ,
          63.45865 ,  64.01172 ],
        [ 84.60792 ,  81.237305,  84.397865, ..., 213.27448 ,
         192.15489 ,  77.688484],
        [241.8698  , 152.16438 , 147.69733 , ...,  61.51829 ,
           0.      ,   0.      ],
        [137.21152 , 108.78419 , 101.13605 , ...,  94.74967 ,
          66.70082 ,  58.116264],
        [350.99075 , 416.07452 , 467.6056  , ..., 470.18506 ,
           0.      ,   0.      ]],

       [[644.29144 , 646.5273  , 637

In [23]:
v

array([[[2198.9973   , 2251.608    , 2169.4185   , ...,    5.4105263,
            7.042105 ,    8.155263 ],
        [  17.102633 ,    7.523684 ,   10.578947 , ...,   48.62105  ,
          696.6816   ,   11.186842 ],
        [1117.3263   ,   22.094736 ,    5.5026317, ...,  378.45     ,
            0.       ,    0.       ],
        [ 453.77896  ,   14.484211 ,   15.565789 , ...,    7.0815787,
           21.621052 ,    4.9342103],
        [ 814.6816   ,  378.69473  ,  270.       , ...,  276.37894  ,
            0.       ,    0.       ]],

       [[2198.9973   , 2251.608    , 2169.4185   , ...,    5.4105263,
            7.042105 ,    8.155263 ],
        [  17.102633 ,    7.523684 ,   10.578947 , ...,   48.62105  ,
          696.6816   ,   11.186842 ],
        [1117.3263   ,   22.094736 ,    5.5026317, ...,  378.45     ,
            0.       ,    0.       ],
        [ 453.77896  ,   14.484211 ,   15.565789 , ...,    7.0815787,
           21.621052 ,    4.9342103],
        [ 814.6816   ,  37

In [19]:
m

array([[[198.55, 199.15, 196.45, ...,  19.6 ,  19.9 ,  20.05],
        [ 26.45,  25.55,  26.5 , ...,  67.1 ,  55.05,  24.35],
        [ 69.2 ,  47.9 ,  46.65, ...,   4.35,   0.  ,   0.  ],
        [ 38.1 ,  34.2 ,  31.75, ...,  29.85,  20.6 ,  18.25],
        [107.45, 130.2 , 147.  , ..., 147.8 ,   0.  ,   0.  ]],

       [[198.55, 199.15, 196.45, ...,  19.6 ,  19.9 ,  20.05],
        [ 26.45,  25.55,  26.5 , ...,  67.1 ,  55.05,  24.35],
        [ 69.2 ,  47.9 ,  46.65, ...,   4.35,   0.  ,   0.  ],
        [ 38.1 ,  34.2 ,  31.75, ...,  29.85,  20.6 ,  18.25],
        [107.45, 130.2 , 147.  , ..., 147.8 ,   0.  ,   0.  ]],

       [[198.55, 199.15, 196.45, ...,  19.6 ,  19.9 ,  20.05],
        [ 26.45,  25.55,  26.5 , ...,  67.1 ,  55.05,  24.35],
        [ 69.2 ,  47.9 ,  46.65, ...,   4.35,   0.  ,   0.  ],
        [ 38.1 ,  34.2 ,  31.75, ...,  29.85,  20.6 ,  18.25],
        [107.45, 130.2 , 147.  , ..., 147.8 ,   0.  ,   0.  ]],

       ...,

       [[198.55, 199.15, 196.45, ...

In [20]:
w

array([[[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.]],

       [[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.]],

       [[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.]],

       ...,

       [[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.]],

       [[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 

In [30]:
r[0][0]

array([644.29144 , 646.5273  , 637.6014  , 541.54456 ,  65.757126,
        66.63708 ,  70.22108 ,  66.64458 , 123.19294 , 455.65338 ,
       443.5871  , 507.92963 , 358.15988 ,  98.17332 ,  82.870384,
        76.48856 ,  74.833145,  62.39391 ,  63.45865 ,  64.01172 ],
      dtype=float32)

In [29]:
r[0], v[0], m[0], e[0]

(array([[644.29144 , 646.5273  , 637.6014  , 541.54456 ,  65.757126,
          66.63708 ,  70.22108 ,  66.64458 , 123.19294 , 455.65338 ,
         443.5871  , 507.92963 , 358.15988 ,  98.17332 ,  82.870384,
          76.48856 ,  74.833145,  62.39391 ,  63.45865 ,  64.01172 ],
        [ 84.60792 ,  81.237305,  84.397865,  98.75221 , 105.58882 ,
         388.08505 , 447.66672 , 463.11877 , 411.6631  , 174.64964 ,
         152.52213 , 150.71663 , 153.40633 , 436.61996 , 325.98697 ,
         303.47406 , 243.48717 , 213.27448 , 192.15489 ,  77.688484],
        [241.8698  , 152.16438 , 147.69733 , 155.7482  , 144.7964  ,
         146.2703  , 464.82846 , 667.4736  , 367.4221  , 487.6269  ,
         403.29767 , 378.81592 , 383.89713 , 300.25906 , 305.48322 ,
         337.66107 , 261.27188 ,  61.51829 ,   0.      ,   0.      ],
        [137.21152 , 108.78419 , 101.13605 ,  84.01785 ,  71.21797 ,
          74.44125 ,  76.1643  ,  82.188805, 110.02273 , 563.25214 ,
         380.33078 , 437.87042 

In [33]:
g=pd.DataFrame()
for i in range(5):
    g[i+1]=pd.concat([pd.Series(r[0][i]), pd.Series(v[0][i]), pd.Series(m[0][i]), pd.Series(e[0][i])], ignore_index=True)

In [34]:
g.head()

1           2           3           4           5
0  644.291443   84.607918  241.869797  137.211517  350.990753
1  646.527283   81.237305  152.164383  108.784187  416.074524
2  637.601379   84.397865  147.697327  101.136047  467.605591
3  541.544556   98.752213  155.748199   84.017853  442.079193
4   65.757126  105.588821  144.796402   71.217972  491.907013

In [35]:
g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   1       80 non-null     float32
 1   2       80 non-null     float32
 2   3       80 non-null     float32
 3   4       80 non-null     float32
 4   5       80 non-null     float32
dtypes: float32(5)
memory usage: 1.7 KB


In [38]:
g[60:80]

1       2       3       4       5
60  3971.0   529.0  1384.0   762.0  2149.0
61  3983.0   511.0   958.0   684.0  2604.0
62  3929.0   530.0   933.0   635.0  2940.0
63  2859.0   620.0   983.0   528.0  2780.0
64   414.0   664.0   914.0   448.0  3099.0
65   419.0  2414.0   922.0   469.0  3066.0
66   442.0  2803.0  2331.0   480.0  2461.0
67   419.0  2908.0  4138.0   514.0   358.0
68   571.0  2533.0  2304.0   694.0   347.0
69  2752.0  1095.0  2984.0  3428.0   369.0
70  2779.0   962.0  2522.0  2367.0   459.0
71  3081.0   949.0  2315.0  2675.0  1146.0
72  2221.0   967.0  2384.0  2850.0  3818.0
73   586.0  2376.0  1897.0  2008.0  3412.0
74   521.0  2047.0  1924.0  1173.0  3500.0
75   481.0  1911.0  2108.0   687.0  3415.0
76   470.0  1528.0  1648.0   666.0  2979.0
77   392.0  1342.0    87.0   597.0  2956.0
78   398.0  1101.0     0.0   412.0     0.0
79   401.0   487.0     0.0   365.0     0.0