In [1]:
import pandas as pd

file=pd.read_csv(r'C:\rahul\rahul\NITK\Semester IV\IET_project\samples\samples2.csv')

In [2]:
file.columns

Index(['sample', 'op_cl_op1', 'op_cl_op2', 'op_cl_op3', 'op_cl_op4',
       'op_cl_op5', 'op_cl_op6', 'op_cl_op7', 'op_cl_op8', 'op_cl_op9',
       ...
       'pn_op_pn13', 'pn_op_pn14', 'pn_op_pn15', 'pn_op_pn16', 'pn_op_pn17',
       'pn_op_pn18', 'pn_op_pn19', 'pn_op_pn20', 'pn_op_pn21', 'pn_op_pn22'],
      dtype='object', length=109)

In [3]:
sample_legend={1:'op_cl_op',2:'cl_rd_cl',3:'ex_fl_ex',4:'sp_pr_sp',5:'pn_op_pn'}
filepath=r'C:\rahul\rahul\NITK\Semester IV\IET_project\gesture'

In [4]:
for i in range(5):
    for j in range(22):
        l=1
        if j>=11:
            l=2
            j=j-11
        fold_n='\p'+str(j+1)
        file_n='\g'+str(i+1)+'t'+str(l)+'.csv'
        col_n=sample_legend[i+1]+str(j+1)
        path=filepath+fold_n+file_n
        #print(repr(path))
        f=file[col_n]
        f.to_csv(path,columns=[col_n],index=False)

In [5]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 762 entries, 0 to 761
Columns: 109 entries, sample to pn_op_pn22
dtypes: float64(108), int64(1)
memory usage: 649.0 KB


In [6]:
file.isnull().sum()

sample        355
op_cl_op1     356
op_cl_op2     376
op_cl_op3     319
op_cl_op4     361
             ... 
pn_op_pn18    378
pn_op_pn19    414
pn_op_pn20    415
pn_op_pn21    398
pn_op_pn22    360
Length: 109, dtype: int64

In [7]:
file.describe()

sample   op_cl_op1   op_cl_op2   op_cl_op3   op_cl_op4   op_cl_op5  \
count  407.000000  406.000000  386.000000  443.000000  401.000000  355.000000   
mean   204.000000   76.891626   52.606218   92.223476  135.294264   39.126761   
std    117.635029   76.917869   29.723756   94.507378  110.019286   30.068345   
min      1.000000    1.000000   16.000000   21.000000   46.000000    2.000000   
25%    102.500000   21.000000   36.000000   46.000000   72.000000   19.000000   
50%    204.000000   25.000000   40.000000   55.000000   77.000000   24.000000   
75%    305.500000  141.000000   65.750000   64.000000  198.000000   58.000000   
max    407.000000  231.000000  134.000000  465.000000  484.000000  133.000000   

        op_cl_op6   op_cl_op7   op_cl_op8   op_cl_op9  ...  pn_op_pn13  \
count  358.000000  349.000000  401.000000  354.000000  ...  353.000000   
mean    45.424581  170.071633  150.079800  334.288136  ...  423.501416   
std     35.938068   87.814414   32.990735   18.485934  ...   19.117627   
min     16.000000    0.000000    7.000000  302.000000  ...  387.000000   
25%     24.000000  132.000000  132.000000  319.000000  ...  408.000000   
50%     28.500000  140.000000  136.000000  336.000000  ...  423.000000   
75%     63.750000  172.000000  161.000000  346.000000  ...  440.000000   
max    382.000000  633.000000  301.000000  389.000000  ...  469.000000   

       pn_op_pn14  pn_op_pn15  pn_op_pn16  pn_op_pn17  pn_op_pn18  pn_op_pn19  \
count  368.000000  310.000000  375.000000  412.000000  384.000000  348.000000   
mean   435.510870  295.861290  281.506667  322.548544  330.927083  369.836207   
std     28.166397    7.376389   23.548660   31.231653   29.245069   16.209513   
min      0.000000  282.000000    1.000000    3.000000    7.000000  334.000000   
25%    422.000000  291.000000  271.000000  313.000000  326.000000  357.000000   
50%    436.000000  295.000000  284.000000  318.000000  333.000000  372.000000   
75%    448.000000  299.000000  292.000000  326.000000  340.000000  382.000000   
max    478.000000  323.000000  305.000000  413.000000  360.000000  410.000000   

       pn_op_pn20  pn_op_pn21  pn_op_pn22  
count  347.000000  364.000000  402.000000  
mean   377.723343  178.532967  397.101990  
std     11.535750   19.901313   47.117956  
min    347.000000    2.000000    7.000000  
25%    370.000000  168.000000  382.000000  
50%    378.000000  177.000000  393.000000  
75%    386.000000  191.000000  406.000000  
max    417.000000  214.000000  610.000000  

[8 rows x 109 columns]

In [8]:
N=400
l=20
p=N/l


In [10]:
p=pd.DataFrame()
for j in range(11):
    for i in range(5):
        l=1
        filepath=r'C:\rahul\rahul\NITK\Semester IV\IET_project\gesture'
        filepath=r'C:\rahul\rahul\NITK\Semester IV\IET_project\gesture\p1'
        #fold_n='\p'+str(j+1)
        file_n='\g'+str(i+1)+'t'+str(l)+'.csv'
        col_n=sample_legend[i+1]+str(1)
        #path=filepath+fold_n+file_n
        path=filepath+file_n
        #pd_n='f'+
        #print(repr(path))
        f=pd.read_csv(path,index_col=False)
        p[col_n]=f
#p.head()    

In [11]:
p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 762 entries, 0 to 761
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   op_cl_op1  406 non-null    float64
 1   cl_rd_cl1  407 non-null    float64
 2   ex_fl_ex1  341 non-null    float64
 3   sp_pr_sp1  762 non-null    int64  
 4   pn_op_pn1  360 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 29.9 KB


In [12]:
p1=p[:400]

In [13]:
p1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   op_cl_op1  400 non-null    float64
 1   cl_rd_cl1  400 non-null    float64
 2   ex_fl_ex1  341 non-null    float64
 3   sp_pr_sp1  400 non-null    int64  
 4   pn_op_pn1  360 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 15.8 KB


In [15]:
p1=p1.fillna(0)

In [14]:
N=400
l=20
p=int(N/l)
import numpy as np

In [16]:
from statistics import variance as var
from statistics import mean as mean

def rms(x):
    # x is array of 20 elements
    r,s=0,0
    for i in range(20):
        s+=x[i]**2
    r=np.sqrt(s/2)
    return r

#def var(x):
    # x is array of 20 elements

In [17]:
st=0
r=np.zeros((11,5,20),dtype=np.float32)
v=np.zeros((11,5,20),dtype=np.float32)
m=np.zeros((11,5,20),dtype=np.float32)
w=np.zeros((11,5,20))
print(p)
for k in range(11):
    for i in range(5):
        st=0
        for j in range(p):
            x=list(p1[sample_legend[i+1]+str(1)][st:st+l])
            #print(x, st)
            r[k][i][j]=rms(x)
            print(r[0][i][j])
            v[k][i][j]=var(x)
            print(v[0][i][j])
            m[k][i][j]=mean(x)
            print(m[0][i][j])
            w[k][i][j]=len(x)
            st=st+l
            if (p-j)==1:
                break
        

20
644.29144
2198.9973
198.55
646.5273
2251.608
199.15
637.6014
2169.4185
196.45
541.54456
9360.366
142.95
65.757126
4.1157894
20.7
66.63708
5.4184213
20.95
70.22108
4.936842
22.1
66.64458
5.523684
20.95
123.19294
739.5237
28.55
455.65338
1924.4631
137.6
443.5871
389.31317
138.95
507.92963
2176.6816
154.05
358.15988
521.8395
111.05
98.17332
110.85263
29.3
82.870384
8.576316
26.05
76.48856
6.9973683
24.05
74.833145
8.157895
23.5
62.39391
5.4105263
19.6
63.45865
7.042105
19.9
64.01172
8.155263
20.05
84.60792
17.102633
26.45
81.237305
7.523684
25.55
84.397865
10.578947
26.5
98.75221
14.947369
31.0
105.58882
13.326316
33.2
388.08505
518.4316
120.7
447.66672
419.50262
140.15
463.11877
322.88422
145.4
411.6631
954.1342
126.65
174.64964
55.460526
54.75
152.52213
13.357895
48.1
150.71663
21.102633
47.45
153.40633
16.45
48.35
436.61996
5210.8
118.8
325.98697
159.18684
102.35
303.47406
84.05
95.55
243.48717
96.46316
76.4
213.27448
48.62105
67.1
192.15489
696.6816
55.05
77.688484
11.186842
24.35


325.98697
159.18684
102.35
303.47406
84.05
95.55
243.48717
96.46316
76.4
213.27448
48.62105
67.1
192.15489
696.6816
55.05
77.688484
11.186842
24.35
241.8698
1117.3263
69.2
152.16438
22.094736
47.9
147.69733
5.5026317
46.65
155.7482
10.5552635
49.15
144.7964
8.536842
45.7
146.2703
15.042106
46.1
464.82846
8444.893
116.55
667.4736
1836.3053
206.9
367.4221
240.90526
115.2
487.6269
1597.2211
149.2
403.29767
382.83157
126.1
378.81592
1002.1974
115.75
383.89713
556.9053
119.2
300.25906
20.028948
94.85
305.48322
81.642105
96.2
337.66107
307.72632
105.4
261.27188
38.463158
82.4
61.51829
378.45
4.35
0.0
0.0
0.0
0.0
0.0
0.0
137.21152
453.77896
38.1
108.78419
14.484211
34.2
101.13605
15.565789
31.75
84.01785
9.410526
26.4
71.21797
5.726316
22.4
74.44125
4.4710526
23.45
76.1643
4.3157897
24.0
82.188805
15.8
25.7
110.02273
6.7473683
34.7
563.25214
2470.8843
171.4
380.33078
482.55527
118.35
437.87042
1351.5658
133.75
459.1035
811.9474
142.5
318.7601
84.88421
100.4
194.30002
353.08157
58.65
108.9977


In [18]:
r

array([[[644.29144 , 646.5273  , 637.6014  , ...,  62.39391 ,
          63.45865 ,  64.01172 ],
        [ 84.60792 ,  81.237305,  84.397865, ..., 213.27448 ,
         192.15489 ,  77.688484],
        [241.8698  , 152.16438 , 147.69733 , ...,  61.51829 ,
           0.      ,   0.      ],
        [137.21152 , 108.78419 , 101.13605 , ...,  94.74967 ,
          66.70082 ,  58.116264],
        [350.99075 , 416.07452 , 467.6056  , ..., 470.18506 ,
           0.      ,   0.      ]],

       [[644.29144 , 646.5273  , 637.6014  , ...,  62.39391 ,
          63.45865 ,  64.01172 ],
        [ 84.60792 ,  81.237305,  84.397865, ..., 213.27448 ,
         192.15489 ,  77.688484],
        [241.8698  , 152.16438 , 147.69733 , ...,  61.51829 ,
           0.      ,   0.      ],
        [137.21152 , 108.78419 , 101.13605 , ...,  94.74967 ,
          66.70082 ,  58.116264],
        [350.99075 , 416.07452 , 467.6056  , ..., 470.18506 ,
           0.      ,   0.      ]],

       [[644.29144 , 646.5273  , 637

In [19]:
v

array([[[2198.9973   , 2251.608    , 2169.4185   , ...,    5.4105263,
            7.042105 ,    8.155263 ],
        [  17.102633 ,    7.523684 ,   10.578947 , ...,   48.62105  ,
          696.6816   ,   11.186842 ],
        [1117.3263   ,   22.094736 ,    5.5026317, ...,  378.45     ,
            0.       ,    0.       ],
        [ 453.77896  ,   14.484211 ,   15.565789 , ...,    7.0815787,
           21.621052 ,    4.9342103],
        [ 814.6816   ,  378.69473  ,  270.       , ...,  276.37894  ,
            0.       ,    0.       ]],

       [[2198.9973   , 2251.608    , 2169.4185   , ...,    5.4105263,
            7.042105 ,    8.155263 ],
        [  17.102633 ,    7.523684 ,   10.578947 , ...,   48.62105  ,
          696.6816   ,   11.186842 ],
        [1117.3263   ,   22.094736 ,    5.5026317, ...,  378.45     ,
            0.       ,    0.       ],
        [ 453.77896  ,   14.484211 ,   15.565789 , ...,    7.0815787,
           21.621052 ,    4.9342103],
        [ 814.6816   ,  37

In [20]:
m

array([[[198.55, 199.15, 196.45, ...,  19.6 ,  19.9 ,  20.05],
        [ 26.45,  25.55,  26.5 , ...,  67.1 ,  55.05,  24.35],
        [ 69.2 ,  47.9 ,  46.65, ...,   4.35,   0.  ,   0.  ],
        [ 38.1 ,  34.2 ,  31.75, ...,  29.85,  20.6 ,  18.25],
        [107.45, 130.2 , 147.  , ..., 147.8 ,   0.  ,   0.  ]],

       [[198.55, 199.15, 196.45, ...,  19.6 ,  19.9 ,  20.05],
        [ 26.45,  25.55,  26.5 , ...,  67.1 ,  55.05,  24.35],
        [ 69.2 ,  47.9 ,  46.65, ...,   4.35,   0.  ,   0.  ],
        [ 38.1 ,  34.2 ,  31.75, ...,  29.85,  20.6 ,  18.25],
        [107.45, 130.2 , 147.  , ..., 147.8 ,   0.  ,   0.  ]],

       [[198.55, 199.15, 196.45, ...,  19.6 ,  19.9 ,  20.05],
        [ 26.45,  25.55,  26.5 , ...,  67.1 ,  55.05,  24.35],
        [ 69.2 ,  47.9 ,  46.65, ...,   4.35,   0.  ,   0.  ],
        [ 38.1 ,  34.2 ,  31.75, ...,  29.85,  20.6 ,  18.25],
        [107.45, 130.2 , 147.  , ..., 147.8 ,   0.  ,   0.  ]],

       ...,

       [[198.55, 199.15, 196.45, ...

In [21]:
w

array([[[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.]],

       [[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.]],

       [[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.]],

       ...,

       [[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 20., 20.]],

       [[20., 20., 20., ..., 20., 20., 20.],
        [20., 20., 20., ..., 20., 